version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  rebase-strategy: disabled
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  rebase-strategy: disabled
