pipeline {
  agent {
    kubernetes {
      yamlFile 'ci/kubernetes.yaml'
    }
  }

  options {
    timeout(time: 20, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  stages {
    stage('Build') {
      steps {
        container('maven') {
          mvn goal: 'clean integration-test', dependencies: 'dependencies/maven.deps'
        }
      }
    }

    stage('Process Licenses') {
      steps {
        container('maven') {
          collectDependencies()
        }
      }
    }

    stage('Deploy Snapshot')
    {
      when {
        anyOf {
          buildingTag()
          branch 'main'
        }
      }
      steps {
        deployP2Site name: 'toolboxmodel', path: 'java/bundles/org.eclipse.set.toolboxmodel.repository/target/repository' 
      }
    }
  }
  post {
    always {
      // Publish JUnit test result
      junit testResults: 'java/bundles/*/target/surefire-reports/*.xml', allowEmptyResults: true
      recordIssues aggregatingResults: true, 
        enabledForFailure: true, 
        tools: [
          checkStyle(), 
          mavenConsole()],
        qualityGates: [[threshold: 1, type: 'TOTAL', unstable: true]]
    }
  }
}