pipeline {
  agent {
    kubernetes {
      label 'set-toolboxmodel-agent-pod'
      yamlFile 'kubernetes.yaml'
    }
  }

  options {
    timeout(time: 20, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  stages {
    stage('Build') {
      steps {
        container('maven') {
          mvn goal: 'clean integration-test'
        }
      }
    }

    stage('Deploy Snapshot')
    {
      when {
        anyOf {
          buildingTag()
          branch 'main'
        }
      }
      steps {
        deployP2Site name: 'toolboxmodel', path: 'java/bundles/org.eclipse.set.toolboxmodel.repository/target/repository' 
      }
    }
  }
}