name: Update DEPENDENCIES

on: 
  repository_dispatch:
  push:
    branches:
      - main
      - release/*

jobs:
  dependencies:
    uses: eclipse-set/build/.github/workflows/update-dependencies.yml@main
    permissions:
      contents: write
